//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientApp.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/WebService.DTOs")]
    [System.SerializableAttribute()]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ArticleNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ManifactureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ArticleNumber {
            get {
                return this.ArticleNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ArticleNumberField, value) != true)) {
                    this.ArticleNumberField = value;
                    this.RaisePropertyChanged("ArticleNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Manifacture {
            get {
                return this.ManifactureField;
            }
            set {
                if ((object.ReferenceEquals(this.ManifactureField, value) != true)) {
                    this.ManifactureField = value;
                    this.RaisePropertyChanged("Manifacture");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceResult", Namespace="http://schemas.datacontract.org/2004/07/WebService.DTOs")]
    [System.SerializableAttribute()]
    public partial class ServiceResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientApp.ServiceReference.Product ProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientApp.ServiceReference.Product[] ProductsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientApp.ServiceReference.ServiceCode StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientApp.ServiceReference.Product Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientApp.ServiceReference.Product[] Products {
            get {
                return this.ProductsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductsField, value) != true)) {
                    this.ProductsField = value;
                    this.RaisePropertyChanged("Products");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientApp.ServiceReference.ServiceCode Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceCode", Namespace="http://schemas.datacontract.org/2004/07/WebService.DTOs")]
    public enum ServiceCode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OK = 200,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NOTFOUND = 404,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EXISTS = 409,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ERROR = 500,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ADDED = 501,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DELETED = 502,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UPDATED = 503,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IProductService")]
    public interface IProductService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/AddProductToList", ReplyAction="http://tempuri.org/IProductService/AddProductToListResponse")]
        ClientApp.ServiceReference.ServiceResult AddProductToList(ClientApp.ServiceReference.Product product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/AddProductToList", ReplyAction="http://tempuri.org/IProductService/AddProductToListResponse")]
        System.Threading.Tasks.Task<ClientApp.ServiceReference.ServiceResult> AddProductToListAsync(ClientApp.ServiceReference.Product product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/GetProductsFromList", ReplyAction="http://tempuri.org/IProductService/GetProductsFromListResponse")]
        ClientApp.ServiceReference.ServiceResult GetProductsFromList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/GetProductsFromList", ReplyAction="http://tempuri.org/IProductService/GetProductsFromListResponse")]
        System.Threading.Tasks.Task<ClientApp.ServiceReference.ServiceResult> GetProductsFromListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/GetProductFromList", ReplyAction="http://tempuri.org/IProductService/GetProductFromListResponse")]
        ClientApp.ServiceReference.ServiceResult GetProductFromList(string articleNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/GetProductFromList", ReplyAction="http://tempuri.org/IProductService/GetProductFromListResponse")]
        System.Threading.Tasks.Task<ClientApp.ServiceReference.ServiceResult> GetProductFromListAsync(string articleNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/UpdateProductInList", ReplyAction="http://tempuri.org/IProductService/UpdateProductInListResponse")]
        ClientApp.ServiceReference.ServiceResult UpdateProductInList(ClientApp.ServiceReference.Product product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/UpdateProductInList", ReplyAction="http://tempuri.org/IProductService/UpdateProductInListResponse")]
        System.Threading.Tasks.Task<ClientApp.ServiceReference.ServiceResult> UpdateProductInListAsync(ClientApp.ServiceReference.Product product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/DeleteProductFromList", ReplyAction="http://tempuri.org/IProductService/DeleteProductFromListResponse")]
        ClientApp.ServiceReference.ServiceResult DeleteProductFromList(string articleNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/DeleteProductFromList", ReplyAction="http://tempuri.org/IProductService/DeleteProductFromListResponse")]
        System.Threading.Tasks.Task<ClientApp.ServiceReference.ServiceResult> DeleteProductFromListAsync(string articleNumber);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProductServiceChannel : ClientApp.ServiceReference.IProductService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductServiceClient : System.ServiceModel.ClientBase<ClientApp.ServiceReference.IProductService>, ClientApp.ServiceReference.IProductService {
        
        public ProductServiceClient() {
        }
        
        public ProductServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ClientApp.ServiceReference.ServiceResult AddProductToList(ClientApp.ServiceReference.Product product) {
            return base.Channel.AddProductToList(product);
        }
        
        public System.Threading.Tasks.Task<ClientApp.ServiceReference.ServiceResult> AddProductToListAsync(ClientApp.ServiceReference.Product product) {
            return base.Channel.AddProductToListAsync(product);
        }
        
        public ClientApp.ServiceReference.ServiceResult GetProductsFromList() {
            return base.Channel.GetProductsFromList();
        }
        
        public System.Threading.Tasks.Task<ClientApp.ServiceReference.ServiceResult> GetProductsFromListAsync() {
            return base.Channel.GetProductsFromListAsync();
        }
        
        public ClientApp.ServiceReference.ServiceResult GetProductFromList(string articleNumber) {
            return base.Channel.GetProductFromList(articleNumber);
        }
        
        public System.Threading.Tasks.Task<ClientApp.ServiceReference.ServiceResult> GetProductFromListAsync(string articleNumber) {
            return base.Channel.GetProductFromListAsync(articleNumber);
        }
        
        public ClientApp.ServiceReference.ServiceResult UpdateProductInList(ClientApp.ServiceReference.Product product) {
            return base.Channel.UpdateProductInList(product);
        }
        
        public System.Threading.Tasks.Task<ClientApp.ServiceReference.ServiceResult> UpdateProductInListAsync(ClientApp.ServiceReference.Product product) {
            return base.Channel.UpdateProductInListAsync(product);
        }
        
        public ClientApp.ServiceReference.ServiceResult DeleteProductFromList(string articleNumber) {
            return base.Channel.DeleteProductFromList(articleNumber);
        }
        
        public System.Threading.Tasks.Task<ClientApp.ServiceReference.ServiceResult> DeleteProductFromListAsync(string articleNumber) {
            return base.Channel.DeleteProductFromListAsync(articleNumber);
        }
    }
}
